"""
Objective Manager — lifecycle tracking for game objectives.
Adapted from Zork-Opus objectives.py.

Objectives are generated by the Strategist agent and tracked here.
Completion is checked via LLM or rule-based heuristics.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional

from ..state import GameState, Objective

logger = logging.getLogger(__name__)


class ObjectiveManager:
    """Manages objective lifecycle: creation, tracking, completion, abandonment."""

    def __init__(self, config, llm_client=None):
        self.config = config
        self.llm = llm_client

    async def check_completions(self, gs: GameState, deltas) -> List[str]:
        """Check if any active objectives were completed this turn.

        Uses rule-based checks first (fast), then LLM for complex conditions.
        Returns list of completed objective IDs.
        """
        completed_ids: List[str] = []

        for obj in gs.active_objectives:
            completed = self._check_rule_based(obj, gs, deltas)

            if completed:
                obj.status = "completed"
                obj.completed_turn = gs.turn_count
                completed_ids.append(obj.id)
                logger.info(f"Objective completed: [{obj.id}] {obj.name} at turn {gs.turn_count}")

        return completed_ids

    def _check_rule_based(self, obj: Objective, gs: GameState, deltas) -> bool:
        """Rule-based completion checking (fast, no LLM)."""
        condition = obj.completion_condition.lower()

        # Badge objectives
        if "badge" in condition and "earned" in condition:
            for badge_name in ["boulder", "cascade", "thunder", "rainbow",
                                "soul", "marsh", "volcano", "earth"]:
                if badge_name in condition and badge_name.capitalize() in gs.badges:
                    return True

        # Party count objectives
        if "party has" in condition:
            import re
            match = re.search(r"party has (\d+)", condition)
            if match and len(gs.party) >= int(match.group(1)):
                return True

        # Pokedex objectives
        if "pokedex" in condition and "received" in condition:
            if gs.has_pokedex:
                return True

        # Item objectives
        if "delivered" in condition and "parcel" in condition:
            # Check via flags
            if gs.has_pokedex:  # Pokedex is received after parcel delivery
                return True

        # Location objectives
        if "reach" in condition or "arrive" in condition:
            for badge_city in ["pewter", "cerulean", "vermilion", "celadon",
                                "fuchsia", "saffron", "cinnabar", "viridian"]:
                if badge_city in condition and badge_city in gs.map_name.lower():
                    return True

        # Level objectives
        if "level" in condition and gs.party:
            import re
            match = re.search(r"level\s*(\d+)", condition)
            if match:
                target_level = int(match.group(1))
                if any(p.level >= target_level for p in gs.party):
                    return True

        # Catch objectives
        if deltas and deltas.pokemon_caught:
            if deltas.pokemon_caught.lower() in condition:
                return True

        return False

    async def check_completions_llm(self, gs: GameState) -> List[str]:
        """LLM-based completion checking for complex objectives.

        Called less frequently (every N turns) as a supplement to rule-based checks.
        """
        if not self.llm or not gs.active_objectives:
            return []

        active = gs.active_objectives
        obj_text = "\n".join(
            f"  [{o.id}] {o.name}: {o.text}\n    COMPLETE WHEN: {o.completion_condition}"
            for o in active
        )

        # Recent history
        history = "\n".join(
            f"  T{e.turn} @ {e.map_name}: {e.actions[:3]}... — {e.reasoning[:60]}"
            for e in gs.action_history[-5:]
        )

        context = f"""Current state:
  Location: {gs.map_name}
  Badges: {gs.badge_count} — {', '.join(gs.badges) if gs.badges else 'none'}
  Party: {', '.join(f'{p.species} Lv{p.level}' for p in gs.party)}
  Pokedex: {gs.pokedex_owned} owned

Active Objectives:
{obj_text}

Recent Actions:
{history}"""

        try:
            result = await self.llm.chat_json(
                role="memory",  # Reuse memory model for objective checking
                messages=[{"role": "user", "content": context}],
                system=OBJECTIVE_CHECK_PROMPT,
            )
            parsed = result["parsed"]

            usage = result.get("usage", {})
            gs.total_tokens += usage.get("input_tokens", 0) + usage.get("output_tokens", 0)

            completed_ids: List[str] = []
            for update in parsed.get("updates", []):
                obj_id = update.get("objective_id")
                if update.get("completed"):
                    for obj in active:
                        if obj.id == obj_id:
                            obj.status = "completed"
                            obj.completed_turn = gs.turn_count
                            completed_ids.append(obj_id)
                            logger.info(
                                f"Objective completed (LLM): [{obj.id}] {obj.name} — "
                                f"{update.get('reason', 'no reason')}"
                            )

            return completed_ids

        except Exception as e:
            logger.warning(f"LLM objective check failed: {e}")
            return []

    def add_objective(self, gs: GameState, objective: Objective) -> None:
        """Add a new objective to the game state."""
        gs.objectives.append(objective)
        logger.info(f"Objective added: [{objective.id}] {objective.name}")

    def abandon_objective(self, gs: GameState, obj_id: str) -> bool:
        """Abandon an objective by ID."""
        for obj in gs.objectives:
            if obj.id == obj_id and obj.status in ("pending", "in_progress"):
                obj.status = "abandoned"
                logger.info(f"Objective abandoned: [{obj.id}] {obj.name}")
                return True
        return False


OBJECTIVE_CHECK_PROMPT = """Review whether any objectives have been completed based on the current game state.

Each objective has a "COMPLETE WHEN" condition. Check that condition against the current state.

Response format:
```json
{
    "reasoning": "Brief analysis of each objective's status",
    "updates": [
        {"objective_id": "OBJ-001", "completed": true, "reason": "Player has Boulder Badge"},
        {"objective_id": "OBJ-002", "completed": false, "reason": "Still need 2 more levels"}
    ]
}
```

Only mark an objective as completed if its specific condition is clearly met.
"""
